### ISSUE TITLE
How to add code tools to this repo?

### ISSUE THREAD

**Issue by JeremyJeanson** [Fitbit/ossapps#109]
Hi,

I would like to add an extension for Visual Studio Code to this repo. But it has none category for that.

The [Fitbit SDK Extension for vscode](https://marketplace.visualstudio.com/items?itemName=JeremyJeanson.fitbit-sdk-extension), allows developers to have all SVG code snippets from the Fitbit documentation and code completion.

Please, Could I push a pull request for that in a category like "tools"?

**Comment by orviwan** [comment]
I've added a Tools section at the end of the readme, please submit.
